---
downloads: ~/.ansible-downloads/

configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/tenfourty/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Documents/dev/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitconfig
  - .gitignore
  - .inputrc
  - .vimrc

homebrew_installed_packages:
  - autoconf
  - bash-completion
  - gettext
  - git
  - gpg
  - iperf
  - nmap
  - npm
  - nvm
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - wget
  - wrk
  - highlight
  - brew-cask-completion
  - archey

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/binary
  - homebrew/dupes
  - homebrew/versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - dropbox
  # - fing # Download link keeps getting changed, d'oh!
  - firefox
  - google-chrome
  - macvim
  - skitch
  - slack
  - transmit
  - vagrant
  - virtualbox
  - istat-menus
  - lastpass
  - flux
  - aerial
  - alfred
  - blue-jeans-launcher
  - cleanmymac
  - insync
  - libreoffice
  - mailplane
  - rocket-chat
  - whatsapp


# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 946399090, name: "Telegram Desktop" }
  - { id: 1039633667, name: "Irvue" }
mas_email: ""
mas_password: ""
