---
downloads: ~/.ansible-downloads/

configure_dotfiles: no
configure_sudoers: no
configure_terminal: no
configure_osx: no

dotfiles_repo: https://github.com/tenfourty/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/QJeremy/dev/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitconfig
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - gettext
  - git
  - gpg
  - iperf
  - nmap
  - npm
  - nvm
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - wget
  - wrk
  - highlight
  - brew-cask-completion
  - archey
  - hugo
  - media-info
  - libdvdcss

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - caskroom/drivers
  - caskroom/fonts
  - homebrew/binary
  - homebrew/dupes
  - homebrew/versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - dropbox
  - firefox
  - google-chrome
  - macvim
  - skitch
  - slack
  - transmit
  - vagrant
  - virtualbox
  - virtualbox-extension-pack
  - istat-menus
  - flux
  - aerial
  - alfred
  - blue-jeans-launcher
  - cleanmymac
  - insync
  - libreoffice
  - mailplane
  - rocket-chat
  - whatsapp
  - blue-jeans-browser-plugin
  - blue-jeans-launcher
  - hyperdock
  - spotify
  - vlc
  - transmission
  - flash-player
  - sketchup
  - sonos
  - xquartz
  - viscosity
  - font-overpass
  - font-liberation-sans
  - sourcetree
  - handbrake
  - xmind
  - transmission-remote-gui
  - the-unarchiver
  - font-liberation-sans
  - font-liberation-mono-for-powerline


# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 747648890, name: "Telegram" }
  - { id: 1039633667, name: "Irvue" }
  - { id: 926036361, name: "LastPass" }
  - { id: 577205158, name: "OnkyMote" }
  - { id: 920404675, name: "Monodraw" }
  - { id: 867299399, name: "OmniFocus" }
  - { id: 405399194, name: "Kindle" }
  - { id: 623795237, name: "Ulysses" }
  - { id: 412386481, name: "VisualDiffer" }
  - { id: 409789998, name: "Twitter" }
  - { id: 406056744, name: "Evernote" }
  - { id: 497799835, name: "XCode" }
  - { id: 425955336, name: "Skitch" }
  
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
